apiVersion: skaffold/v1beta10
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
  artifacts:
    - image: eu.gcr.io/ventura-cluster/go-automated-test
      context: ./GO
